services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: yostream-mediamtx
    restart: unless-stopped
    ports:
      - "1935:1935"
      - "8554:8554"
      - "8888:8888"
      - "8889:8889"
      - "8189:8189/udp"
      - "9997:9997"
      - "9996:9996"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./recordings:/recordings
    environment:
      MTX_API: "yes"
      MTX_APIADDRESS: ":9997"
      MTX_PLAYBACK: "yes"
      MTX_PLAYBACKADDRESS: ":9996"
      MTX_HLSADDRESS: ":8888"
      MTX_WEBRTCADDRESS: ":8889"
      MTX_RTMPADDRESS: ":1935"
      MTX_RTSPADDRESS: ":8554"
